#!/usr/bin/env bash
while (true); do
	read -p "First score: " fscore
	read -p "Second score: " sscore
	scores=( "\$fscore" "\$sscore" )
	for number in "${scores[@]}"; do
		if [ "$number" == "\$fscore" ]; then
			var=$fscore;
		elif [ "$number" == "\$sscore" ]; then
			var=$sscore;
		fi
		case $var in
			0)
				prob=.1604;; 
			1)
				prob=.0943 ;;
			2)
				prob=.0236 ;;
			3)
				prob=.0849 ;;
			4)
				prob=.1651 ;;
			5)
				prob=.0236 ;;
			6)
				prob=.0849 ;;
			7)
				prob=.2358 ;;
			8)
				prob=.0708 ;;
			9)
				prob=.0566 ;;
			*)
				echo $number
		esac;
		if [ "$number" == "\$fscore" ]; then
			fprob=$prob;
		elif [ "$number" == "\$sscore" ]; then
			sprob=$prob;
		fi
	done;
	ans=$(echo "(${sprob}*${fprob})*100" |bc)
	echo ${ans}%;
done;
