#!/usr/bin/env bash

read -p "First score: " fscore
read -p "Second score: " sscore
	
case "$fscore" in
	0)
		fprob=.1604 ;;
	1)
		fprob=.0943 ;;
	2)
		fprob=.0236 ;;
	3)
		fprob=.0849 ;;
	4)
		fprob=.1651 ;;
	5)
		fprob=.0236 ;;
	6)
		fprob=.0849 ;;
	7)
		fprob=.2358 ;;
	8)
		fprob=.0708 ;;
	9)
		fprob=.0566 ;;
esac;
case "$sscore" in
	0)
		sprob=.1604 ;;
	1)
		sprob=.0943 ;;
	2)
		sprob=.0236 ;;
	3)
		sprob=.0849 ;;
	4)
		sprob=.1651 ;;
	5)
		sprob=.0236 ;;
	6)
		sprob=.0849 ;;
	7)
		sprob=.2358 ;;
	8)
		sprob=.0708 ;;
	9)
		sprob=.0566;;
esac;
ans=$(echo "(${sprob}*${fprob})*100" |bc)
pc="%";

echo ${ans}${pc};
